trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:
- script: echo "Hello World"
  displayName: "Run a one line script"
- script: |
    echo "Testing Public Repo Access"
    git ls-remote https://github.com/Bhoopesh123/Grafana

    echo "Private Repo in Git"
    # git ls-remote https://github.com/Bhoopesh123/awstest
    git ls-remote git@github.com:username/Bhoopesh123/awstest 
    # git clone https://Bhoopesh123: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@github.com/Bhoopesh123/awstest

